# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MathsforDataScience
email: shivamogili1728@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Join Shiva Mogili as he explores the intricate world of Data Science, delving into key concepts of statistics, probability, and calculus. This blog aims to equip aspiring data scientists with the fundamental knowledge and skills needed to excel in the field. Dive into our comprehensive guides and prepare effectively with our specialized content on interview questions for Data Science and Machine Learning roles.
baseurl: "MathforDatascience" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  https://github.com/shivareddy0117

# Build settings
theme: minima
plugins:
  - jekyll-feed
default:
  - 
    scopes:
      path: ""
      type: "post"
    values:
       layout: "post"
       title: "My-title"  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
